apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: requirenodeselectors
spec:
  crd:
    spec:
      names:
        kind: RequireNodeSelectors
        listKind: RequireNodeSelectorsList
        plural: requirenodeselectors
        singular: requirenodeselector

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package requirenodeselectors

        # seems to be working
        violation[{"msg": msg, "details": {"missing_prefix": "nodeSelector"}}] {
          hasNodeSelector
          msg := sprintf("you must provide nodeSelector: %v", ["test"])
        }

        hasNodeSelector {
          input.review.object.spec.template.spec.nodeSelector
          count(input.review.object.spec.template.spec.nodeSelector) > 0
        }

        # not working
        violation[{"msg": msg, "details": {"missing_prefix": "nodeSelector"}}] {
          provided := {nodeselector | input.review.object.spec.template.spec.nodeSelector[nodeselector]}
          required := { test }
          missing := required - provided
          count(missing) > 0
          msg := sprintf("new one: %v", ["test"])
        }
